//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.24 at 09:06:22 AM CET 
//


package eu.eubrazilcc.lvl.core.xml.ncbi.gb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.eubrazilcc.lvl.core.xml.ncbi.gb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.eubrazilcc.lvl.core.xml.ncbi.gb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GBCommentParagraph }
     * 
     */
    public GBCommentParagraph createGBCommentParagraph() {
        return new GBCommentParagraph();
    }

    /**
     * Create an instance of {@link GBAltSeqData }
     * 
     */
    public GBAltSeqData createGBAltSeqData() {
        return new GBAltSeqData();
    }

    /**
     * Create an instance of {@link GBAltSeqDataItems }
     * 
     */
    public GBAltSeqDataItems createGBAltSeqDataItems() {
        return new GBAltSeqDataItems();
    }

    /**
     * Create an instance of {@link GBXref }
     * 
     */
    public GBXref createGBXref() {
        return new GBXref();
    }

    /**
     * Create an instance of {@link GBSeqXrefs }
     * 
     */
    public GBSeqXrefs createGBSeqXrefs() {
        return new GBSeqXrefs();
    }

    /**
     * Create an instance of {@link GBSeqFeatureTable }
     * 
     */
    public GBSeqFeatureTable createGBSeqFeatureTable() {
        return new GBSeqFeatureTable();
    }

    /**
     * Create an instance of {@link GBFeature }
     * 
     */
    public GBFeature createGBFeature() {
        return new GBFeature();
    }

    /**
     * Create an instance of {@link GBCommentParagraphs }
     * 
     */
    public GBCommentParagraphs createGBCommentParagraphs() {
        return new GBCommentParagraphs();
    }

    /**
     * Create an instance of {@link GBFeatureQuals }
     * 
     */
    public GBFeatureQuals createGBFeatureQuals() {
        return new GBFeatureQuals();
    }

    /**
     * Create an instance of {@link GBQualifier }
     * 
     */
    public GBQualifier createGBQualifier() {
        return new GBQualifier();
    }

    /**
     * Create an instance of {@link GBAltSeqItem }
     * 
     */
    public GBAltSeqItem createGBAltSeqItem() {
        return new GBAltSeqItem();
    }

    /**
     * Create an instance of {@link GBAltSeqItemInterval }
     * 
     */
    public GBAltSeqItemInterval createGBAltSeqItemInterval() {
        return new GBAltSeqItemInterval();
    }

    /**
     * Create an instance of {@link GBAltSeqItemIsgap }
     * 
     */
    public GBAltSeqItemIsgap createGBAltSeqItemIsgap() {
        return new GBAltSeqItemIsgap();
    }

    /**
     * Create an instance of {@link GBSeq }
     * 
     */
    public GBSeq createGBSeq() {
        return new GBSeq();
    }

    /**
     * Create an instance of {@link GBSeqOtherSeqids }
     * 
     */
    public GBSeqOtherSeqids createGBSeqOtherSeqids() {
        return new GBSeqOtherSeqids();
    }

    /**
     * Create an instance of {@link GBSeqSecondaryAccessions }
     * 
     */
    public GBSeqSecondaryAccessions createGBSeqSecondaryAccessions() {
        return new GBSeqSecondaryAccessions();
    }

    /**
     * Create an instance of {@link GBSeqKeywords }
     * 
     */
    public GBSeqKeywords createGBSeqKeywords() {
        return new GBSeqKeywords();
    }

    /**
     * Create an instance of {@link GBSeqReferences }
     * 
     */
    public GBSeqReferences createGBSeqReferences() {
        return new GBSeqReferences();
    }

    /**
     * Create an instance of {@link GBSeqCommentSet }
     * 
     */
    public GBSeqCommentSet createGBSeqCommentSet() {
        return new GBSeqCommentSet();
    }

    /**
     * Create an instance of {@link GBSeqStrucComments }
     * 
     */
    public GBSeqStrucComments createGBSeqStrucComments() {
        return new GBSeqStrucComments();
    }

    /**
     * Create an instance of {@link GBSeqFeatureSet }
     * 
     */
    public GBSeqFeatureSet createGBSeqFeatureSet() {
        return new GBSeqFeatureSet();
    }

    /**
     * Create an instance of {@link GBSeqAltSeq }
     * 
     */
    public GBSeqAltSeq createGBSeqAltSeq() {
        return new GBSeqAltSeq();
    }

    /**
     * Create an instance of {@link GBInterval }
     * 
     */
    public GBInterval createGBInterval() {
        return new GBInterval();
    }

    /**
     * Create an instance of {@link GBIntervalIscomp }
     * 
     */
    public GBIntervalIscomp createGBIntervalIscomp() {
        return new GBIntervalIscomp();
    }

    /**
     * Create an instance of {@link GBIntervalInterbp }
     * 
     */
    public GBIntervalInterbp createGBIntervalInterbp() {
        return new GBIntervalInterbp();
    }

    /**
     * Create an instance of {@link GBSet }
     * 
     */
    public GBSet createGBSet() {
        return new GBSet();
    }

    /**
     * Create an instance of {@link GBKeyword }
     * 
     */
    public GBKeyword createGBKeyword() {
        return new GBKeyword();
    }

    /**
     * Create an instance of {@link GBFeatureIntervals }
     * 
     */
    public GBFeatureIntervals createGBFeatureIntervals() {
        return new GBFeatureIntervals();
    }

    /**
     * Create an instance of {@link GBFeaturePartial5 }
     * 
     */
    public GBFeaturePartial5 createGBFeaturePartial5() {
        return new GBFeaturePartial5();
    }

    /**
     * Create an instance of {@link GBFeaturePartial3 }
     * 
     */
    public GBFeaturePartial3 createGBFeaturePartial3() {
        return new GBFeaturePartial3();
    }

    /**
     * Create an instance of {@link GBFeatureXrefs }
     * 
     */
    public GBFeatureXrefs createGBFeatureXrefs() {
        return new GBFeatureXrefs();
    }

    /**
     * Create an instance of {@link GBFeatureSet }
     * 
     */
    public GBFeatureSet createGBFeatureSet() {
        return new GBFeatureSet();
    }

    /**
     * Create an instance of {@link GBFeatureSetFeatures }
     * 
     */
    public GBFeatureSetFeatures createGBFeatureSetFeatures() {
        return new GBFeatureSetFeatures();
    }

    /**
     * Create an instance of {@link GBStrucComment }
     * 
     */
    public GBStrucComment createGBStrucComment() {
        return new GBStrucComment();
    }

    /**
     * Create an instance of {@link GBStrucCommentItems }
     * 
     */
    public GBStrucCommentItems createGBStrucCommentItems() {
        return new GBStrucCommentItems();
    }

    /**
     * Create an instance of {@link GBSeqid }
     * 
     */
    public GBSeqid createGBSeqid() {
        return new GBSeqid();
    }

    /**
     * Create an instance of {@link GBReferenceAuthors }
     * 
     */
    public GBReferenceAuthors createGBReferenceAuthors() {
        return new GBReferenceAuthors();
    }

    /**
     * Create an instance of {@link GBAuthor }
     * 
     */
    public GBAuthor createGBAuthor() {
        return new GBAuthor();
    }

    /**
     * Create an instance of {@link GBReference }
     * 
     */
    public GBReference createGBReference() {
        return new GBReference();
    }

    /**
     * Create an instance of {@link GBReferenceXref }
     * 
     */
    public GBReferenceXref createGBReferenceXref() {
        return new GBReferenceXref();
    }

    /**
     * Create an instance of {@link GBStrucCommentItem }
     * 
     */
    public GBStrucCommentItem createGBStrucCommentItem() {
        return new GBStrucCommentItem();
    }

    /**
     * Create an instance of {@link GBSecondaryAccn }
     * 
     */
    public GBSecondaryAccn createGBSecondaryAccn() {
        return new GBSecondaryAccn();
    }

    /**
     * Create an instance of {@link GBComment }
     * 
     */
    public GBComment createGBComment() {
        return new GBComment();
    }

}
