language: java

jdk:
  - oraclejdk8

sudo: required

cache:
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.embedmongo

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - sudo mkdir -p /opt/lvl/var/log/lvl
  - sudo chown -R `whoami`.`whoami` /opt/lvl/var/log/lvl
  - mvn install:install-file -Dfile=pom.xml -DpomFile=pom.xml
  - mvn clean install -pl lvl-project
