//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.02 at 01:47:04 PM CEST 
//


package eu.eubrazilcc.lvl.core.xml.ncbi.esearch;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "term",
    "field",
    "count",
    "explode"
})
@XmlRootElement(name = "TermSet")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
public class TermSet {

    @XmlElement(name = "Term", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    protected String term;
    @XmlElement(name = "Field", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    protected String field;
    @XmlElement(name = "Count", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    protected Count count;
    @XmlElement(name = "Explode", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    protected String explode;

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public String getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public void setField(String value) {
        this.field = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Count }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public Count getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Count }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public void setCount(Count value) {
        this.count = value;
    }

    /**
     * Gets the value of the explode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public String getExplode() {
        return explode;
    }

    /**
     * Sets the value of the explode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public void setExplode(String value) {
        this.explode = value;
    }

}
