//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.02 at 01:47:04 PM CEST 
//


package eu.eubrazilcc.lvl.core.xml.ncbi.esearch;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "from",
    "to"
})
@XmlRootElement(name = "Translation")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
public class Translation {

    @XmlElement(name = "From", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    protected String from;
    @XmlElement(name = "To", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    protected String to;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-05-02T01:47:04+02:00", comments = "JAXB RI v2.2.4-2")
    public void setTo(String value) {
        this.to = value;
    }

}
