/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package eu.eubrazilcc.lvl.service.avro.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ImportDataCommand { 
  MANAGER_RUN, IMPORTER_RUN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ImportDataCommand\",\"namespace\":\"eu.eubrazilcc.lvl.service.avro.messages\",\"symbols\":[\"MANAGER_RUN\",\"IMPORTER_RUN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
