/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package eu.eubrazilcc.lvl.service.avro.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class QueryHistory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"QueryHistory\",\"namespace\":\"eu.eubrazilcc.lvl.service.avro.messages\",\"fields\":[{\"name\":\"webEnv\",\"type\":\"string\"},{\"name\":\"queryKey\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.CharSequence webEnv;
   private java.lang.CharSequence queryKey;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public QueryHistory() {}

  /**
   * All-args constructor.
   */
  public QueryHistory(java.lang.CharSequence webEnv, java.lang.CharSequence queryKey) {
    this.webEnv = webEnv;
    this.queryKey = queryKey;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return webEnv;
    case 1: return queryKey;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: webEnv = (java.lang.CharSequence)value$; break;
    case 1: queryKey = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'webEnv' field.
   */
  public java.lang.CharSequence getWebEnv() {
    return webEnv;
  }

  /**
   * Sets the value of the 'webEnv' field.
   * @param value the value to set.
   */
  public void setWebEnv(java.lang.CharSequence value) {
    this.webEnv = value;
  }

  /**
   * Gets the value of the 'queryKey' field.
   */
  public java.lang.CharSequence getQueryKey() {
    return queryKey;
  }

  /**
   * Sets the value of the 'queryKey' field.
   * @param value the value to set.
   */
  public void setQueryKey(java.lang.CharSequence value) {
    this.queryKey = value;
  }

  /** Creates a new QueryHistory RecordBuilder */
  public static eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder newBuilder() {
    return new eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder();
  }
  
  /** Creates a new QueryHistory RecordBuilder by copying an existing Builder */
  public static eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder newBuilder(eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder other) {
    return new eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder(other);
  }
  
  /** Creates a new QueryHistory RecordBuilder by copying an existing QueryHistory instance */
  public static eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder newBuilder(eu.eubrazilcc.lvl.service.avro.messages.QueryHistory other) {
    return new eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder(other);
  }
  
  /**
   * RecordBuilder for QueryHistory instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<QueryHistory>
    implements org.apache.avro.data.RecordBuilder<QueryHistory> {

    private java.lang.CharSequence webEnv;
    private java.lang.CharSequence queryKey;

    /** Creates a new Builder */
    private Builder() {
      super(eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.webEnv)) {
        this.webEnv = data().deepCopy(fields()[0].schema(), other.webEnv);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.queryKey)) {
        this.queryKey = data().deepCopy(fields()[1].schema(), other.queryKey);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing QueryHistory instance */
    private Builder(eu.eubrazilcc.lvl.service.avro.messages.QueryHistory other) {
            super(eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.SCHEMA$);
      if (isValidValue(fields()[0], other.webEnv)) {
        this.webEnv = data().deepCopy(fields()[0].schema(), other.webEnv);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.queryKey)) {
        this.queryKey = data().deepCopy(fields()[1].schema(), other.queryKey);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'webEnv' field */
    public java.lang.CharSequence getWebEnv() {
      return webEnv;
    }
    
    /** Sets the value of the 'webEnv' field */
    public eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder setWebEnv(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.webEnv = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'webEnv' field has been set */
    public boolean hasWebEnv() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'webEnv' field */
    public eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder clearWebEnv() {
      webEnv = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'queryKey' field */
    public java.lang.CharSequence getQueryKey() {
      return queryKey;
    }
    
    /** Sets the value of the 'queryKey' field */
    public eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder setQueryKey(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.queryKey = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'queryKey' field has been set */
    public boolean hasQueryKey() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'queryKey' field */
    public eu.eubrazilcc.lvl.service.avro.messages.QueryHistory.Builder clearQueryKey() {
      queryKey = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public QueryHistory build() {
      try {
        QueryHistory record = new QueryHistory();
        record.webEnv = fieldSetFlags()[0] ? this.webEnv : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.queryKey = fieldSetFlags()[1] ? this.queryKey : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
