//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.27 at 05:37:46 PM CET 
//


package eu.eubrazilcc.lvl.core.xml.tdwg.tapir;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


/**
 * Format of metadata operation result.
 * 
 * <p>Java class for metadataResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadataResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}type"/&gt;
 *         &lt;element name="accesspoint" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}language" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}subject" minOccurs="0"/&gt;
 *         &lt;element ref="{http://purl.org/dc/terms/}bibliographicCitation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}rights" minOccurs="0"/&gt;
 *         &lt;element ref="{http://purl.org/dc/terms/}modified" minOccurs="0"/&gt;
 *         &lt;element ref="{http://purl.org/dc/terms/}created" minOccurs="0"/&gt;
 *         &lt;element name="indexingPreferences" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="startTime" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
 *                 &lt;attribute name="maxDuration" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *                 &lt;attribute name="frequency" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="relatedEntity" type="{http://rs.tdwg.org/tapir/1.0}relatedEntityInformationType" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://rs.tdwg.org/tapir/1.0}custom" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadataResultType", propOrder = {
    "title",
    "type",
    "accesspoint",
    "description",
    "language",
    "subject",
    "bibliographicCitation",
    "rights",
    "modified",
    "created",
    "indexingPreferences",
    "relatedEntity",
    "custom"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
public class MetadataResultType {

    @XmlElementRef(name = "title", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected JAXBElement<SimpleLiteral> title;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected SimpleLiteral type;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected String accesspoint;
    @XmlElementRef(name = "description", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected JAXBElement<SimpleLiteral> description;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected List<SimpleLiteral> language;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected SimpleLiteral subject;
    @XmlElement(namespace = "http://purl.org/dc/terms/")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected SimpleLiteral bibliographicCitation;
    @XmlElementRef(name = "rights", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected JAXBElement<SimpleLiteral> rights;
    @XmlElement(namespace = "http://purl.org/dc/terms/")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected SimpleLiteral modified;
    @XmlElement(namespace = "http://purl.org/dc/terms/")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected SimpleLiteral created;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected MetadataResultType.IndexingPreferences indexingPreferences;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected List<RelatedEntityInformationType> relatedEntity;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected Custom custom;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    protected String lang;

    /**
     * The name of this service possibly in different
     * 					languages.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public JAXBElement<SimpleLiteral> getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setTitle(JAXBElement<SimpleLiteral> value) {
        this.title = value;
    }

    /**
     * The nature or genre of the content of the resource. 
     * 						http://purl.org/dc/dcmitype/Service
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public SimpleLiteral getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setType(SimpleLiteral value) {
        this.type = value;
    }

    /**
     * Gets the value of the accesspoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public String getAccesspoint() {
        return accesspoint;
    }

    /**
     * Sets the value of the accesspoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setAccesspoint(String value) {
        this.accesspoint = value;
    }

    /**
     * Description may include but is not limited to: an abstract,
     * 						table of contents, reference to a graphical representation
     * 						of content or a free-text account of the content.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public JAXBElement<SimpleLiteral> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setDescription(JAXBElement<SimpleLiteral> value) {
        this.description = value;
    }

    /**
     * Language of content that can be returned by search 
     * 						and inventory responses. This element must follow RFC 4646 
     * 						and use language codes specified by the IANA Language Subtag 
     * 						Registry. More than one language can be specified, in case 
     * 						the provider can serve content in multiple languages. When 
     * 						there is no linguistic content, "zxx" must be used.Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleLiteral }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public List<SimpleLiteral> getLanguage() {
        if (language == null) {
            language = new ArrayList<SimpleLiteral>();
        }
        return this.language;
    }

    /**
     * Subject and Keywords. Typically, a Subject will be expressed as keywords,
     * 						key phrases or classification codes that describe a topic
     * 						of the resource. Recommended best practice is to select 
     * 						a value from a controlled vocabulary or formal 
     * 						classification scheme
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public SimpleLiteral getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setSubject(SimpleLiteral value) {
        this.subject = value;
    }

    /**
     * Recommended practice is to include sufficient 
     * 						bibliographic detail to identify the resource as 
     * 						unambiguously as possible, whether or not the
     * 						citation is in a standard form.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public SimpleLiteral getBibliographicCitation() {
        return bibliographicCitation;
    }

    /**
     * Sets the value of the bibliographicCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setBibliographicCitation(SimpleLiteral value) {
        this.bibliographicCitation = value;
    }

    /**
     * Information about who can access the
     * 						resource or an indication of its security status.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public JAXBElement<SimpleLiteral> getRights() {
        return rights;
    }

    /**
     * Sets the value of the rights property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setRights(JAXBElement<SimpleLiteral> value) {
        this.rights = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public SimpleLiteral getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setModified(SimpleLiteral value) {
        this.modified = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public SimpleLiteral getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setCreated(SimpleLiteral value) {
        this.created = value;
    }

    /**
     * Gets the value of the indexingPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataResultType.IndexingPreferences }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType.IndexingPreferences getIndexingPreferences() {
        return indexingPreferences;
    }

    /**
     * Sets the value of the indexingPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataResultType.IndexingPreferences }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setIndexingPreferences(MetadataResultType.IndexingPreferences value) {
        this.indexingPreferences = value;
    }

    /**
     * Gets the value of the relatedEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedEntityInformationType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public List<RelatedEntityInformationType> getRelatedEntity() {
        if (relatedEntity == null) {
            relatedEntity = new ArrayList<RelatedEntityInformationType>();
        }
        return this.relatedEntity;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link Custom }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public Custom getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Custom }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setCustom(Custom value) {
        this.custom = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public void setLang(String value) {
        this.lang = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withTitle(JAXBElement<SimpleLiteral> value) {
        setTitle(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withType(SimpleLiteral value) {
        setType(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withAccesspoint(String value) {
        setAccesspoint(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withDescription(JAXBElement<SimpleLiteral> value) {
        setDescription(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withLanguage(SimpleLiteral... values) {
        if (values!= null) {
            for (SimpleLiteral value: values) {
                getLanguage().add(value);
            }
        }
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withLanguage(Collection<SimpleLiteral> values) {
        if (values!= null) {
            getLanguage().addAll(values);
        }
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withSubject(SimpleLiteral value) {
        setSubject(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withBibliographicCitation(SimpleLiteral value) {
        setBibliographicCitation(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withRights(JAXBElement<SimpleLiteral> value) {
        setRights(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withModified(SimpleLiteral value) {
        setModified(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withCreated(SimpleLiteral value) {
        setCreated(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withIndexingPreferences(MetadataResultType.IndexingPreferences value) {
        setIndexingPreferences(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withRelatedEntity(RelatedEntityInformationType... values) {
        if (values!= null) {
            for (RelatedEntityInformationType value: values) {
                getRelatedEntity().add(value);
            }
        }
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withRelatedEntity(Collection<RelatedEntityInformationType> values) {
        if (values!= null) {
            getRelatedEntity().addAll(values);
        }
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withCustom(Custom value) {
        setCustom(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public MetadataResultType withLang(String value) {
        setLang(value);
        return this;
    }

    @Override
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

    @Override
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public boolean equals(Object that) {
        return EqualsBuilder.reflectionEquals(this, that);
    }

    @Override
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="startTime" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
     *       &lt;attribute name="maxDuration" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
     *       &lt;attribute name="frequency" type="{http://www.w3.org/2001/XMLSchema}duration" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
    public static class IndexingPreferences {

        @XmlAttribute(name = "startTime")
        @XmlSchemaType(name = "time")
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        protected XMLGregorianCalendar startTime;
        @XmlAttribute(name = "maxDuration")
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        protected Duration maxDuration;
        @XmlAttribute(name = "frequency")
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        protected Duration frequency;

        /**
         * Gets the value of the startTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public XMLGregorianCalendar getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public void setStartTime(XMLGregorianCalendar value) {
            this.startTime = value;
        }

        /**
         * Gets the value of the maxDuration property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public Duration getMaxDuration() {
            return maxDuration;
        }

        /**
         * Sets the value of the maxDuration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public void setMaxDuration(Duration value) {
            this.maxDuration = value;
        }

        /**
         * Gets the value of the frequency property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public Duration getFrequency() {
            return frequency;
        }

        /**
         * Sets the value of the frequency property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public void setFrequency(Duration value) {
            this.frequency = value;
        }

        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public MetadataResultType.IndexingPreferences withStartTime(XMLGregorianCalendar value) {
            setStartTime(value);
            return this;
        }

        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public MetadataResultType.IndexingPreferences withMaxDuration(Duration value) {
            setMaxDuration(value);
            return this;
        }

        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public MetadataResultType.IndexingPreferences withFrequency(Duration value) {
            setFrequency(value);
            return this;
        }

        @Override
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public String toString() {
            return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
        }

        @Override
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public boolean equals(Object that) {
            return EqualsBuilder.reflectionEquals(this, that);
        }

        @Override
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-27T05:37:46+01:00", comments = "JAXB RI v2.2.11")
        public int hashCode() {
            return HashCodeBuilder.reflectionHashCode(this);
        }

    }

}
