//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 08:19:58 PM CEST 
//


package eu.eubrazilcc.lvl.core.xml.ncbi;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbIntervalFrom",
    "gbIntervalTo",
    "gbIntervalPoint",
    "gbIntervalIscomp",
    "gbIntervalInterbp",
    "gbIntervalAccession"
})
@XmlRootElement(name = "GBInterval")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
public class GBInterval {

    @XmlElement(name = "GBInterval_from")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    protected String gbIntervalFrom;
    @XmlElement(name = "GBInterval_to")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    protected String gbIntervalTo;
    @XmlElement(name = "GBInterval_point")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    protected String gbIntervalPoint;
    @XmlElement(name = "GBInterval_iscomp")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    protected GBIntervalIscomp gbIntervalIscomp;
    @XmlElement(name = "GBInterval_interbp")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    protected GBIntervalInterbp gbIntervalInterbp;
    @XmlElement(name = "GBInterval_accession", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    protected String gbIntervalAccession;

    /**
     * Gets the value of the gbIntervalFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public String getGBIntervalFrom() {
        return gbIntervalFrom;
    }

    /**
     * Sets the value of the gbIntervalFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public void setGBIntervalFrom(String value) {
        this.gbIntervalFrom = value;
    }

    /**
     * Gets the value of the gbIntervalTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public String getGBIntervalTo() {
        return gbIntervalTo;
    }

    /**
     * Sets the value of the gbIntervalTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public void setGBIntervalTo(String value) {
        this.gbIntervalTo = value;
    }

    /**
     * Gets the value of the gbIntervalPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public String getGBIntervalPoint() {
        return gbIntervalPoint;
    }

    /**
     * Sets the value of the gbIntervalPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public void setGBIntervalPoint(String value) {
        this.gbIntervalPoint = value;
    }

    /**
     * Gets the value of the gbIntervalIscomp property.
     * 
     * @return
     *     possible object is
     *     {@link GBIntervalIscomp }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public GBIntervalIscomp getGBIntervalIscomp() {
        return gbIntervalIscomp;
    }

    /**
     * Sets the value of the gbIntervalIscomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBIntervalIscomp }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public void setGBIntervalIscomp(GBIntervalIscomp value) {
        this.gbIntervalIscomp = value;
    }

    /**
     * Gets the value of the gbIntervalInterbp property.
     * 
     * @return
     *     possible object is
     *     {@link GBIntervalInterbp }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public GBIntervalInterbp getGBIntervalInterbp() {
        return gbIntervalInterbp;
    }

    /**
     * Sets the value of the gbIntervalInterbp property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBIntervalInterbp }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public void setGBIntervalInterbp(GBIntervalInterbp value) {
        this.gbIntervalInterbp = value;
    }

    /**
     * Gets the value of the gbIntervalAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public String getGBIntervalAccession() {
        return gbIntervalAccession;
    }

    /**
     * Sets the value of the gbIntervalAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-28T08:19:58+02:00", comments = "JAXB RI v2.2.4-2")
    public void setGBIntervalAccession(String value) {
        this.gbIntervalAccession = value;
    }

}
