//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.01 at 03:36:39 PM CET 
//


package eu.eubrazilcc.lvl.core.xml.ncbi.pubmed;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "medlineCitation",
    "deleteCitation"
})
@XmlRootElement(name = "MedlineCitationSet")
public class MedlineCitationSet {

    @XmlElement(name = "MedlineCitation")
    protected List<MedlineCitation> medlineCitation;
    @XmlElement(name = "DeleteCitation")
    protected DeleteCitation deleteCitation;

    /**
     * Gets the value of the medlineCitation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medlineCitation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedlineCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedlineCitation }
     * 
     * 
     */
    public List<MedlineCitation> getMedlineCitation() {
        if (medlineCitation == null) {
            medlineCitation = new ArrayList<MedlineCitation>();
        }
        return this.medlineCitation;
    }

    /**
     * Gets the value of the deleteCitation property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteCitation }
     *     
     */
    public DeleteCitation getDeleteCitation() {
        return deleteCitation;
    }

    /**
     * Sets the value of the deleteCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteCitation }
     *     
     */
    public void setDeleteCitation(DeleteCitation value) {
        this.deleteCitation = value;
    }

    public MedlineCitationSet withMedlineCitation(MedlineCitation... values) {
        if (values!= null) {
            for (MedlineCitation value: values) {
                getMedlineCitation().add(value);
            }
        }
        return this;
    }

    public MedlineCitationSet withMedlineCitation(Collection<MedlineCitation> values) {
        if (values!= null) {
            getMedlineCitation().addAll(values);
        }
        return this;
    }

    public MedlineCitationSet withDeleteCitation(DeleteCitation value) {
        setDeleteCitation(value);
        return this;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

    @Override
    public boolean equals(java.lang.Object that) {
        return EqualsBuilder.reflectionEquals(this, that);
    }

    @Override
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this);
    }

}
