//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.24 at 09:06:22 AM CET 
//


package eu.eubrazilcc.lvl.core.xml.ncbi.pubmed;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "year",
    "month",
    "day",
    "hour",
    "minute",
    "second"
})
@XmlRootElement(name = "PubMedPubDate")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
public class PubMedPubDate {

    @XmlAttribute(name = "PubStatus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    protected String pubStatus;
    @XmlElement(name = "Year", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    protected Year year;
    @XmlElement(name = "Month", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    protected Month month;
    @XmlElement(name = "Day", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    protected Day day;
    @XmlElement(name = "Hour")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    protected String hour;
    @XmlElement(name = "Minute")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    protected String minute;
    @XmlElement(name = "Second")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    protected String second;

    /**
     * Gets the value of the pubStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public String getPubStatus() {
        return pubStatus;
    }

    /**
     * Sets the value of the pubStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public void setPubStatus(String value) {
        this.pubStatus = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Year }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public Year getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Year }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public void setYear(Year value) {
        this.year = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link Month }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public Month getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link Month }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public void setMonth(Month value) {
        this.month = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link Day }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public Day getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link Day }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public void setDay(Day value) {
        this.day = value;
    }

    /**
     * Gets the value of the hour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public String getHour() {
        return hour;
    }

    /**
     * Sets the value of the hour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public void setHour(String value) {
        this.hour = value;
    }

    /**
     * Gets the value of the minute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public String getMinute() {
        return minute;
    }

    /**
     * Sets the value of the minute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public void setMinute(String value) {
        this.minute = value;
    }

    /**
     * Gets the value of the second property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public String getSecond() {
        return second;
    }

    /**
     * Sets the value of the second property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public void setSecond(String value) {
        this.second = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public PubMedPubDate withPubStatus(String value) {
        setPubStatus(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public PubMedPubDate withYear(Year value) {
        setYear(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public PubMedPubDate withMonth(Month value) {
        setMonth(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public PubMedPubDate withDay(Day value) {
        setDay(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public PubMedPubDate withHour(String value) {
        setHour(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public PubMedPubDate withMinute(String value) {
        setMinute(value);
        return this;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public PubMedPubDate withSecond(String value) {
        setSecond(value);
        return this;
    }

    @Override
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

    @Override
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public boolean equals(java.lang.Object that) {
        return EqualsBuilder.reflectionEquals(this, that);
    }

    @Override
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-24T09:06:22+01:00", comments = "JAXB RI v2.2.11")
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this);
    }

}
