//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 12:30:16 PM CEST 
//


package eu.eubrazilcc.lvl.core.xml.tdwg.dwc;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class Language2
    extends JAXBElement<SimpleLiteral>
{

    protected final static QName NAME = new QName("http://purl.org/dc/elements/1.1/", "language");

    public Language2(SimpleLiteral value) {
        super(NAME, ((Class) SimpleLiteral.class), null, value);
    }

    public Language2() {
        super(NAME, ((Class) SimpleLiteral.class), null, null);
    }

}
